### ISSUE TITLE
Item width not being handled accurately

### ISSUE THREAD

**Issue by hubcin** [sephiroth74/HorizontalVariableListView#103]
Setting the width to the outer most parent of my item layout, let's say, a RelativeLayout, I set the width of it to a fixed value, but it seems like this value is getting ignored, the item width is decided by the size of the views inside this RelativeLayout including padding and margin. It makes me hard to control the width of the items, not a big problem itself but I'm facing same problem with my own AdapterView(check this http://stackoverflow.com/questions/29716609/custom-adapter-view-child-not-being-measured-correctly), so I post this issue here hoping you would have any idea on this.Thanks

**Comment by mhsnakdgn** [comment]
did you find any solution to fix items witdth?

**Comment by hubcin** [comment]
> did you find any solution to fix items witdth?

no, sorry, I just gave up on that long ago. But if I do it again now, I would dig into to source code and find out the reason.
