### ISSUE TITLE
Android 8 setOnItemClickListener is not Working when clicked on Image

### ISSUE THREAD

**Issue by ramgopalcheedu** [sephiroth74/HorizontalVariableListView#118]

**Comment by ramgopalcheedu** [comment]
Implemented workaround closing issue

**Comment by kcochibili** [comment]
what was the workaround?

**Comment by kcochibili** [comment]
I found the Solution here: https://github.com/sephiroth74/HorizontalVariableListView/issues/33#issuecomment-93437358

basically you would have to clear focus on all focussable child views in the parent View (that goes into the ListView)
