### ISSUE TITLE
2 days lost trying to understand why item click doesn't work

### ISSUE THREAD

**Issue by veonua** [sephiroth74/HorizontalVariableListView#33]
=(( why did you break compatibility

AdapterView.setOnItemClickListener
and
HorizontalVariableListView.setOnItemClick>>ed<<Listener

it's not trivial to find this little difference, please don't do this in the future.

**Comment by quangson91** [comment]
Add this param to rootView of ItemListView.
android:descendantFocusability="blocksDescendants"

This can help u.

**Comment by Sarzin** [comment]
hi there

i have the same problem when add second listview "setOnItemClickListener" doesn't work.

I have add these in both my  listview :

 android:clickable="false"
android:focusable="false"
 android:descendantFocusability="blocksDescendants"

i try to add "LinearLayout" and "android:layout_weight="1"  " but the result of calling "setOnItemClickListener" is nothing.

i can just call "setOnItemClickListener" for "listView1" and "list_slidermenu" doesn't work.

please help me .......

this is my code:

mainActivity.xml

<android.support.v4.widget.DrawerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <TextView
        android:id="@+id/textView1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Action Bar:"
        android:textAppearance="?android:attr/textAppearanceMedium"
        />
    
    <FrameLayout
        android:id="@+id/frame_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

```
<!-- Listview to display slider menu -->
<ListView
    android:clickable="false"
    android:focusable="false"
    android:descendantFocusability="blocksDescendants"
    android:id="@+id/list_slidermenu"
    android:layout_width="240dp"
    android:layout_height="match_parent"
    android:layout_gravity="start"
    android:choiceMode="singleChoice"
    android:divider="@color/list_divider"
    android:dividerHeight="1dp"        
    android:listSelector="@drawable/list_selector"
    android:background="@color/list_background"/>
<ListView
    android:clickable="false"
    android:focusable="false"
    android:descendantFocusability="blocksDescendants"
    android:visibility="invisible"
    android:id="@+id/listView1"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_alignParentLeft="true"
    android:layout_alignParentTop="true"
    >
</ListView>
```

</android.support.v4.widget.DrawerLayout>

and myactivity.java

protected void onCreate(Bundle savedInstanceState)
 {
....
mDrawerList = (ListView) findViewById(R.id.list_slidermenu);
mDrawerList.setOnItemClickListener(new SlideMenuClickListener());
....
}

private class SlideMenuClickListener implements
            ListView.OnItemClickListener {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position,
                long id) {
            // display view for selected nav drawer item
            displayView(position);
        }
    }

}

**Comment by quangson91** [comment]
you can remove all clickAble && focusable. (then try setOnLongItemClickListener)

**Comment by Sarzin** [comment]
thank you for your replay, i try it before.

can you look at the my small sample.
link:
http://yekvip.com/twolistview.rar

I'm really confused after three days fighting with this two listview :|

**Comment by Sarzin** [comment]
......................................................MainActivity.java........................................................

package info.androidhive.slidingmenu;

import android.app.Activity;
import android.app.Fragment;
import android.app.FragmentManager;
import android.content.res.Configuration;
import android.content.res.TypedArray;
import android.os.Bundle;
import android.support.v4.app.ActionBarDrawerToggle;
import android.support.v4.widget.DrawerLayout;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;

import info.androidhive.slidingmenu.adapter.NavDrawerListAdapter;
import info.androidhive.slidingmenu.model.NavDrawerItem;

public class MainActivity extends Activity {
    private DrawerLayout mDrawerLayout;
    private ListView mDrawerList;
    private ActionBarDrawerToggle mDrawerToggle;

```
// nav drawer title
private CharSequence mDrawerTitle;

// used to store app title
private CharSequence mTitle;

// slide menu items
private String[] navMenuTitles;
private TypedArray navMenuIcons;

private ArrayList<NavDrawerItem> navDrawerItems;
private NavDrawerListAdapter adapter;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    mTitle = mDrawerTitle = getTitle();

    // load slide menu items
    navMenuTitles = getResources().getStringArray(R.array.nav_drawer_items);

    // nav drawer icons from resources
    navMenuIcons = getResources()
            .obtainTypedArray(R.array.nav_drawer_icons);

    mDrawerLayout = (DrawerLayout) findViewById(R.id.drawer_layout);
    mDrawerList = (ListView) findViewById(R.id.list_slidermenu);
    mDrawerList.setOnItemClickListener(new AdapterView.OnItemClickListener() {
        public void onItemClick(AdapterView<?> myAdapter, View myView, int myItemInt, long mylng) {
            String selectedFromList =(String) (mDrawerList.getItemAtPosition(myItemInt));
            // String text = parent.getItemAtPosition(position).toString();
            TextView textView=(TextView)findViewById(R.id.textView1);
            textView.setText(selectedFromList);

            displayView(myItemInt);
            //  displayView(myItemInt);
        }
    });
    navDrawerItems = new ArrayList<NavDrawerItem>();

    // adding nav drawer items to array
    // Home
    navDrawerItems.add(new NavDrawerItem(navMenuTitles[0], navMenuIcons.getResourceId(0, -1)));
    // Find People
    navDrawerItems.add(new NavDrawerItem(navMenuTitles[1], navMenuIcons.getResourceId(1, -1)));
    // Photos
    navDrawerItems.add(new NavDrawerItem(navMenuTitles[2], navMenuIcons.getResourceId(2, -1)));
    // Communities, Will add a counter here
    navDrawerItems.add(new NavDrawerItem(navMenuTitles[3], navMenuIcons.getResourceId(3, -1), true, "22"));
    // Pages
    navDrawerItems.add(new NavDrawerItem(navMenuTitles[4], navMenuIcons.getResourceId(4, -1)));
    // What's hot, We  will add a counter here
    navDrawerItems.add(new NavDrawerItem(navMenuTitles[5], navMenuIcons.getResourceId(5, -1), true, "50+"));


    // Recycle the typed array
    navMenuIcons.recycle();

    mDrawerList.setOnItemClickListener(new SlideMenuClickListener());

    // setting the nav drawer list adapter
    adapter = new NavDrawerListAdapter(getApplicationContext(),
            navDrawerItems);
    mDrawerList.setAdapter(adapter);

    // enabling action bar app icon and behaving it as toggle button
    getActionBar().setDisplayHomeAsUpEnabled(true);
    getActionBar().setHomeButtonEnabled(true);

    mDrawerToggle = new ActionBarDrawerToggle(this, mDrawerLayout,
            R.drawable.ic_drawer, //nav menu toggle icon
            R.string.app_name, // nav drawer open - description for accessibility
            R.string.app_name // nav drawer close - description for accessibility
    ) {
        public void onDrawerClosed(View view) {
            getActionBar().setTitle(mTitle);
            // calling onPrepareOptionsMenu() to show action bar icons
            invalidateOptionsMenu();
        }

        public void onDrawerOpened(View drawerView) {
            getActionBar().setTitle(mDrawerTitle);
            // calling onPrepareOptionsMenu() to hide action bar icons
            invalidateOptionsMenu();
        }
    };
    mDrawerLayout.setDrawerListener(mDrawerToggle);

    if (savedInstanceState == null) {
        // on first time display view for first nav item
        displayView(0);
    }
}

/**
 * Slide menu item click listener
 * */
private class SlideMenuClickListener implements
        ListView.OnItemClickListener {
    @Override
    public void onItemClick(AdapterView<?> parent, View view, int position,
            long id) {
        // display view for selected nav drawer item
        displayView(position);
    }
}

@Override
public boolean onCreateOptionsMenu(Menu menu) {

    return true;
}

@Override
public boolean onOptionsItemSelected(MenuItem item) {
    // toggle nav drawer on selecting action bar app icon/title
    if (mDrawerToggle.onOptionsItemSelected(item)) {
        return true;
    }
    // Handle action bar actions click
    switch (item.getItemId()) {

    default:
        return super.onOptionsItemSelected(item);
    }
}

/* *
 * Called when invalidateOptionsMenu() is triggered
 */
@Override
public boolean onPrepareOptionsMenu(Menu menu) {
    // if nav drawer is opened, hide the action items
    boolean drawerOpen = mDrawerLayout.isDrawerOpen(mDrawerList);
    //menu.findItem(R.id.action_settings).setVisible(!drawerOpen);
    return super.onPrepareOptionsMenu(menu);
}

/**
 * Diplaying fragment view for selected nav drawer list item
 * */
private void displayView(int position) {
    // update the main content by replacing fragments
    String tmpStr10 = Integer.toString(position);
    TextView textView=(TextView)findViewById(R.id.textView1);
    textView.setText(tmpStr10);
    Fragment fragment = null;
    switch (position) {
    case 0:
        fragment = new HomeFragment();
        break;
    case 1:
        fragment = new FindPeopleFragment();
        break;
    case 2:
        fragment = new PhotosFragment();
        break;
    case 3:
        fragment = new CommunityFragment();
        break;
    case 4:
        fragment = new PagesFragment();
        break;
    case 5:
        fragment = new WhatsHotFragment();
        break;

    default:
        break;
    }

    if (fragment != null) {
        FragmentManager fragmentManager = getFragmentManager();
        fragmentManager.beginTransaction()
                .replace(R.id.frame_container, fragment).commit();

        // update selected item and title, then close the drawer
        mDrawerList.setItemChecked(position, true);
        mDrawerList.setSelection(position);
        setTitle(navMenuTitles[position]);
        mDrawerLayout.closeDrawer(mDrawerList);
    } else {
        // error in creating fragment
        Log.e("MainActivity", "Error in creating fragment");
    }
}

@Override
public void setTitle(CharSequence title) {
    mTitle = title;
    getActionBar().setTitle(mTitle);
}

/**
 * When using the ActionBarDrawerToggle, you must call it during
 * onPostCreate() and onConfigurationChanged()...
 */

@Override
protected void onPostCreate(Bundle savedInstanceState) {
    super.onPostCreate(savedInstanceState);
    // Sync the toggle state after onRestoreInstanceState has occurred.
    mDrawerToggle.syncState();
}

@Override
public void onConfigurationChanged(Configuration newConfig) {
    super.onConfigurationChanged(newConfig);
    // Pass any configuration change to the drawer toggls
    mDrawerToggle.onConfigurationChanged(newConfig);
}
```

}

......................................................activity_main.xml........................................................

<android.support.v4.widget.DrawerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:descendantFocusability="blocksDescendants"
    android:clickable="false"
    android:focusable="false"
    >
    <TextView
        android:id="@+id/textView1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Action Bar:"
        android:textAppearance="?android:attr/textAppearanceMedium"
        />
    
    <FrameLayout
        android:id="@+id/frame_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

```
<!-- Listview to display slider menu -->
<ListView

    android:descendantFocusability="blocksDescendants"
    android:id="@+id/list_slidermenu"
    android:layout_width="240dp"
    android:layout_height="match_parent"
    android:layout_gravity="start"
    android:choiceMode="singleChoice"
    android:divider="@color/list_divider"
    android:dividerHeight="1dp"        
    android:listSelector="@drawable/list_selector"
    android:background="@color/list_background"/>
<ListView

    android:descendantFocusability="blocksDescendants"
    android:visibility="invisible"
    android:id="@+id/listView1"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_alignParentLeft="true"
    android:layout_alignParentTop="true"
    >
</ListView>
```

</android.support.v4.widget.DrawerLayout>

**Comment by Sarzin** [comment]
is android studio try to be visual studio?!!
so funny, we can insert multi listview in .Net and how about android?! when we add two listView, It's make error.

android is just for users not developers!

**Comment by Xplouder** [comment]
Thanks god i found this thread! I was debugging a problem similar to this for days. Thank you.

**Comment by thanhhai08sk** [comment]
It takes me almost day. Thank you all very much.
I set clickable and focusable to false and it works for me.

**Comment by veonua** [comment]
use RecycleView from support library.

**Comment by Checkhino** [comment]
hi thank you for the trick but i got always a problem i put focusable to false ans clickable to false 
il work but i have switch on my expandable list view and now the state of swicth can be change because it is not clickable so do you have any solution to my problem
thank you a lot

**Comment by VishalJogiya** [comment]
android:focusable="false"
worked for me

**Comment by Aayesha-Raje** [comment]
android:focusable="false"
    android:clickable="false" dont work for me 
trying from 4 days oniTemclick listener is not working

public class CafesActivity extends AppCompatActivity {


    final ArrayList<Word> word = new ArrayList<Word>();


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.word_list);
        Button b = (Button)findViewById(R.id.button_change);
        Button b1 = (Button)findViewById(R.id.button_change);


        word.add(new Word(R.drawable.brewbrakes, "BrewBakes Cafe"));
        word.add(new Word(R.drawable.rio_la, "Rio La Cafe"));
        word.add(new Word(R.drawable.ccd, "cafe Coffee day"));
        word.add(new Word(R.drawable.cafe_blue, "Cafe Blues"));
        word.add(new Word(R.drawable.noahs_cafe, "Noahs Cafe and \nBistro"));
        word.add(new Word(R.drawable.akkis_burger, "Akki's Burger and Cafe"));
        word.add(new Word(R.drawable.big_bun, "Big Bun Cafe"));

        final WordAdapter adapter = new WordAdapter(this, word, R.color.cafes);


        final ListView listView = (ListView) findViewById(R.id.list);

        listView.setAdapter(adapter);


        listView.setOnItemClickListener(new AdapterView.OnItemClickListener(){
            @Override

            public void onItemClick(AdapterView<?> parent, View v, final int position, long id) {
              if(position==1) {
                  Toast.makeText(getApplicationContext(), "clicked" + position, Toast.LENGTH_LONG).show();
              }
                }
        });



    }
}
sm1 help

**Comment by veonua** [comment]
use RecyclerView instead. this component has no updates for 4 years

**Comment by shaxzodshox** [comment]
> is android studio try to be visual studio?!!
> so funny, we can insert multi listview in .Net and how about android?! when we add two listView, It's make error.
> 
> android is just for users not developers!

fuck u
